//***************************//
//*Template by pulgamecanica*//
//***************************//

#ifndef __CPP_ON_RAILS_HPP__
# define __CPP_ON_RAILS_HPP__

#ifndef DEBUG
# define DEBUG 0
#endif

#define WIDTH 1200
#define HEIGHT 650

#define POSITIONS_FILENAME "cache/nodes_positions.txt"

# define C_BLACK  "\033[0;30m"
# define C_RED    "\033[0;31m"
# define C_GREEN  "\033[0;32m"
# define C_YELLOW "\033[0;33m"
# define C_BLUE   "\033[0;34m"
# define C_WHITE  "\033[0;37m"
# define ENDC   "\033[0m"


#endif
