Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.define "PulgamecanicaS" do |node|  # Define the node
    node.vm.hostname = "PulgamecanicaS"
    # node.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"  # Choose your real interface
    node.vm.network "private_network", ip: "192.168.56.110", adapter: 2  # eth1 interface

    node.vm.provider "virtualbox" do |vb|
      vb.memory = 4096
      vb.cpus = 2
    end
  end
end