Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "Arosado-S" do |node|
    node.vm.hostname = "Arosado-S"
    node.vm.network "private_network", ip: "192.168.56.110", adapter: 2
    
    node.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    node.vm.synced_folder ".", "/vagrant"

    node.vm.provision "file", source: ".env", destination: "/vagrant/.env"
    # Use Ansible for provisioning
    node.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/playbook.yml"
      ansible.inventory_path = "ansible/inventory.ini"
    end
  end
end
