//***************************//
//*Template by pulgamecanica*//
//***************************//

#ifndef __EX00_HPP__
# define __EX00_HPP__

#ifndef DEBUG
# define DEBUG 0
#endif

#include <iostream>


# define BLACK  "\033[0;30m"
# define RED    "\033[0;31m"
# define GREEN  "\033[0;32m"
# define YELLOW "\033[0;33m"
# define BLUE   "\033[0;34m"
# define WHITE  "\033[0;37m"
# define ENDC   "\033[0m"


#endif
