# frozen_string_literal: true

source 'https://rubygems.org'

gem 'base64', '~> 0.2.0'
gem 'bcrypt'
gem 'connection_pool', '~> 2.5'
gem 'dotenv'
gem 'json', '~> 2.10'
gem 'openssl', '~> 3.3'
gem 'pg'
gem 'puma'
gem 'rack'
gem 'rack-test'
gem 'rackup'
gem 'rake'
gem 'rspec'
gem 'securerandom', '~> 0.4.1'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'faraday'

group :development do
  gem 'faker'
  gem 'pry'
  gem 'rubocop', require: false
  gem 'ruby-progressbar'
end
